# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:latest

#options:
#  docker: true

dock: &dock
  services:
    - docker
  caches:
    - docker
    
pipelines:
  branches:
    qa-build/*:
      - step:
          caches:
            - node
          script:
            - yarn install
            - yarn build
            - yarn qa-deploy
          
  custom: # Pipelines that are triggered manually
    build:
      - step:
          caches:
            - node
          script:
            - yarn install
            - yarn build
            
    deploy:
      - step:
          script:
            - yarn install
            - yarn build
            - yarn deploy

    docker-deploy:
      - step:
          <<: *dock
          script:
            ./dock build
            